services:
  litebench:
    build: .
    env_file: .env
    environment:
      - MODEL=openrouter/qwen/qwen3-235b-a22b-2507
      - THINKING_MODEL=openrouter/qwen/qwen3-235b-a22b-thinking-2507
    restart: no
    volumes:
      - .:/app
      - runtime_dir:/root/.litebench
    # ports:
    #   - 8600:8600
    # command: litebench serve --host 0.0.0.0

volumes:
   runtime_dir:
